"""Seed knowledge: 50+ documented failure modes from quant history.

Every entry references a real event, paper, or well-documented
practitioner experience. The format mirrors :class:`Lesson` — id,
category, title, description, symptom, mitigation, severity (1–5),
references, tags.

Categories used:
    overfitting       — model fit noise, not signal
    leakage           — future info contaminated training
    regime_shift      — model trained on regime that no longer exists
    execution         — slippage, fills, partial executions
    risk_sizing       — position size / Kelly mistakes
    correlation       — assumed-independent positions became correlated
    liquidity         — bid/ask widened, couldn't exit
    deployment        — bad code went live
    behavioral        — discretionary override killed the strategy
    data_quality      — bad data in, bad signal out
    counterparty      — broker, exchange, prime broker failures
    macro             — structural regime / policy shock
    crowding          — too many funds in the same trade
"""

from __future__ import annotations

from typing import List, Dict, Any

SEED_LESSONS: List[Dict[str, Any]] = [
    # ----- Overfitting / backtesting hygiene -----
    {
        "id": "l_001",
        "category": "overfitting",
        "title": "Backtest overfitting from too many strategy variations",
        "description": "Trying N variations of a strategy and picking the best by Sharpe gives a fake Sharpe that scales with sqrt(log N). Most published backtests with Sharpe > 2 do not replicate.",
        "symptom": "Best-of-K strategy variations all have Sharpe > 1.5 in-sample; live performance is sub-1.0.",
        "mitigation": "Use deflated Sharpe ratio (Bailey & López de Prado 2014); penalize by number of variations tried; combinatorial purged CV.",
        "severity": 5,
        "references": ["Bailey, Borwein, López de Prado, Zhu (2014)",
                       "Bailey & López de Prado (2014) Deflated Sharpe Ratio"],
        "tags": ["backtest", "ml", "sharpe"],
    },
    {
        "id": "l_002",
        "category": "leakage",
        "title": "Lookahead bias from same-day data",
        "description": "Computing today's signal from today's close and trading at today's close is lookahead. Same applies to fundamentals (earnings released after close used in same-day signal).",
        "symptom": "Backtest dramatically outperforms paper trading; signal magnitude shrinks with execution lag added.",
        "mitigation": "Lag all features by at least one bar. Use point-in-time fundamentals only.",
        "severity": 5,
        "references": ["López de Prado (2018) ch 4"],
        "tags": ["leakage", "backtest"],
    },
    {
        "id": "l_003",
        "category": "leakage",
        "title": "Random K-fold CV on time series",
        "description": "Random shuffling for cross-validation lets the model see the future from the past. Common ML mistake that's catastrophic in finance.",
        "symptom": "CV scores ~0.65, walk-forward / live scores ~0.51.",
        "mitigation": "Use TimeSeriesSplit or purged combinatorial CV. Never shuffle.",
        "severity": 5,
        "references": ["López de Prado (2018) ch 7"],
        "tags": ["leakage", "ml", "cv"],
    },
    {
        "id": "l_004",
        "category": "leakage",
        "title": "Survivorship bias in universe selection",
        "description": "Backtesting on today's S&P 500 components ignores companies that were dropped (often after failing). Inflates returns by 1-3% annually.",
        "symptom": "Long-only backtests on 'large caps' look better than they should.",
        "mitigation": "Use point-in-time index membership data (CRSP, Compustat, or open-source equivalents).",
        "severity": 4,
        "references": ["Elton, Gruber, Blake (1996)"],
        "tags": ["data_quality", "backtest"],
    },
    {
        "id": "l_005",
        "category": "leakage",
        "title": "Target encoding leakage",
        "description": "Using target statistics (e.g., mean return of category) computed on the full dataset leaks future info into features.",
        "symptom": "Categorical features with suspiciously high importance.",
        "mitigation": "Compute target encodings only on the training fold; recompute per fold.",
        "severity": 4,
        "references": ["Kaggle: any target leakage post-mortem"],
        "tags": ["leakage", "ml", "features"],
    },

    # ----- Regime shifts -----
    {
        "id": "l_006",
        "category": "regime_shift",
        "title": "Momentum crash of 2009",
        "description": "After the March 2009 bottom, the cross-sectional momentum factor reversed violently — losers became winners. AQR, Renaissance, and others took 20-30% drawdowns in months.",
        "symptom": "Long-momentum portfolios at multi-year lows during sharp risk-on rebounds.",
        "mitigation": "Add volatility scaling to momentum sizing; reduce exposure when realized vol spikes.",
        "severity": 4,
        "references": ["Daniel & Moskowitz (2016) Momentum Crashes"],
        "tags": ["regime", "momentum", "factor"],
    },
    {
        "id": "l_007",
        "category": "regime_shift",
        "title": "Quant Quake (Aug 6-10, 2007)",
        "description": "Several large quant funds with similar factor exposures faced simultaneous redemptions. Forced de-leveraging cascaded; models lost 6-15% in 3 days against their backtests.",
        "symptom": "Daily losses 4+ standard deviations from backtest; multiple uncorrelated alphas drawing down together.",
        "mitigation": "Stress-test for crowdedness; cap position sizes well below the 'optimal' from backtest.",
        "severity": 5,
        "references": ["Khandani & Lo (2011) What Happened to the Quants in August 2007?"],
        "tags": ["regime", "crowding", "factor"],
    },
    {
        "id": "l_008",
        "category": "regime_shift",
        "title": "2022 rates shock killed long-duration trades",
        "description": "After 14 years of falling rates, the Fed hiking cycle inverted every long-duration carry trade simultaneously. Long bond funds lost 20%+; many factor portfolios with implicit duration exposure also bled.",
        "symptom": "Strategies with no obvious rate exposure correlate strongly with TLT during a regime change.",
        "mitigation": "Decompose alpha into factor exposures; monitor rate sensitivity even for non-rate strategies.",
        "severity": 4,
        "references": ["Various 2022 hedge fund letters"],
        "tags": ["regime", "macro", "duration"],
    },

    # ----- Risk sizing -----
    {
        "id": "l_009",
        "category": "risk_sizing",
        "title": "Full-Kelly is too aggressive in practice",
        "description": "Kelly criterion assumes known probabilities and zero estimation error. Using estimated edge with full Kelly typically leads to >50% drawdowns even with positive expected value.",
        "symptom": "Equity curve has 40%+ drawdowns despite positive long-term return.",
        "mitigation": "Use half-Kelly or quarter-Kelly. Cap any single position at 5% of equity.",
        "severity": 4,
        "references": ["MacLean, Thorp, Ziemba (2010)",
                       "Already implemented in src/risk/risk_manager.py"],
        "tags": ["sizing", "kelly"],
    },
    {
        "id": "l_010",
        "category": "risk_sizing",
        "title": "Long Term Capital Management (1998)",
        "description": "Convergence trades with 25x+ leverage. When Russia defaulted and correlations went to 1, LTCM lost $4.6B in 4 months — required Fed-organized bailout.",
        "symptom": "Multiple 'uncorrelated' positions move together in a stress event.",
        "mitigation": "Stress-test under correlation = 1 assumption; cap gross leverage at 3-5x for retail; never trade convergence at extreme leverage.",
        "severity": 5,
        "references": ["Lowenstein (2000) When Genius Failed"],
        "tags": ["leverage", "crisis", "correlation"],
    },
    {
        "id": "l_011",
        "category": "risk_sizing",
        "title": "Position sizing as fixed dollars vs % of equity",
        "description": "Doubling down on losers (martingale) or fixed-dollar sizing after losses leads to ruin even with positive edge.",
        "symptom": "Position sizes increase after losses.",
        "mitigation": "Always size as % of current equity (not starting equity). Never increase size after a loss.",
        "severity": 5,
        "references": ["Thorp (1969)"],
        "tags": ["sizing", "behavioral"],
    },

    # ----- Execution -----
    {
        "id": "l_012",
        "category": "execution",
        "title": "Knight Capital August 1, 2012",
        "description": "Code deployment error left old SMARS routing logic active. In 45 minutes Knight sent millions of erroneous orders, losing $440M. Firm bankrupt within a week.",
        "symptom": "Order volume spikes wildly above strategy's normal turnover.",
        "mitigation": "Kill-switch on order rate; manual sign-off for deploys; canary deploy with size cap.",
        "severity": 5,
        "references": ["SEC enforcement action 2013"],
        "tags": ["deployment", "execution", "operational"],
    },
    {
        "id": "l_013",
        "category": "execution",
        "title": "Slippage underestimation in backtest",
        "description": "Most backtests assume mid-price fills. Real fills cost 2-30 bps even for liquid names; more for illiquid. A strategy with 1 bp/trade alpha is unprofitable after costs.",
        "symptom": "Backtest Sharpe drops 30-50% when realistic costs added.",
        "mitigation": "Apply 2-5 bps per side for liquid US equities; 10+ for small-caps; vary by spread + size.",
        "severity": 4,
        "references": ["Almgren & Chriss (2000)"],
        "tags": ["execution", "backtest", "costs"],
    },
    {
        "id": "l_014",
        "category": "execution",
        "title": "Stop hunting in thin liquidity",
        "description": "Market makers and HFTs can see stop clusters and push price through them, then revert. Most stops in extended-hours or thinly-traded names hit on noise.",
        "symptom": "Stops hit at intraday lows that immediately reverse.",
        "mitigation": "Use mental stops or wider hard stops in thin markets; avoid round-number stops.",
        "severity": 3,
        "references": ["Hasbrouck (2007)"],
        "tags": ["execution", "stops"],
    },
    {
        "id": "l_015",
        "category": "execution",
        "title": "Flash Crash (May 6, 2010)",
        "description": "$4.1B sell algo caused liquidity vacuum; major indices dropped 9% in minutes then recovered. Stop orders triggered at absurd prices (e.g., Accenture at $0.01).",
        "symptom": "Wild quote anomalies in normal-hours trading.",
        "mitigation": "Avoid market orders during volatile periods; use limit orders with reasonable bands.",
        "severity": 4,
        "references": ["SEC/CFTC 2010 Report"],
        "tags": ["execution", "crisis", "liquidity"],
    },

    # ----- Liquidity / fat tails -----
    {
        "id": "l_016",
        "category": "liquidity",
        "title": "Liquidity vanishes precisely when needed",
        "description": "In crisis, bid/ask widens 10-100x. Your hedges can't be lifted; your underwater positions can't be exited.",
        "symptom": "Spreads widen sharply during P&L stress.",
        "mitigation": "Trade only names with >$10M daily volume; pre-stage exits before vol spikes; maintain cash reserve.",
        "severity": 4,
        "references": ["O'Hara (2015)"],
        "tags": ["liquidity", "crisis"],
    },
    {
        "id": "l_017",
        "category": "liquidity",
        "title": "Tail risk shorts blow up in 1-day events",
        "description": "Selling deep OTM puts/calls for premium has positive expected value most years, then loses 5-10 years of profit in one event (VIX Feb 2018, XIV collapse).",
        "symptom": "Strategy makes small steady gains, then a single day takes 50%+.",
        "mitigation": "Never sell naked vol without delta-hedge or defined risk. Read Taleb 'Dynamic Hedging'.",
        "severity": 5,
        "references": ["Taleb (1997)"],
        "tags": ["options", "tail_risk", "vol_selling"],
    },

    # ----- Crowding / coordinated risk -----
    {
        "id": "l_018",
        "category": "crowding",
        "title": "Gamestop / WSB short squeezes (Jan 2021)",
        "description": "Retail coordination via Reddit forced short covers on heavily-shorted small/mid-caps. Melvin Capital lost 50%+; multiple funds blew up.",
        "symptom": "Short interest > 50% of float in a heavily-discussed-online name.",
        "mitigation": "Avoid concentrated shorts in names with high social-media mention rate.",
        "severity": 4,
        "references": ["Various 2021 hedge fund letters"],
        "tags": ["crowding", "shorting", "retail"],
    },
    {
        "id": "l_019",
        "category": "crowding",
        "title": "Published anomalies decay after publication",
        "description": "McLean & Pontiff (2016): factor returns drop ~32% post-publication and ~58% post-implementation by funds.",
        "symptom": "A strategy you read about in a paper underperforms its backtest in live trading.",
        "mitigation": "Assume any public alpha is half-strength; require larger out-of-sample margin before trusting.",
        "severity": 3,
        "references": ["McLean & Pontiff (2016) Does Academic Research Destroy Stock Return Predictability?"],
        "tags": ["alpha_decay", "factor"],
    },

    # ----- Correlation breakdowns -----
    {
        "id": "l_020",
        "category": "correlation",
        "title": "Diversification fails in crises",
        "description": "Cross-asset correlations spike to 0.8-1.0 during sell-offs. Your 'diversified' portfolio behaves like a single concentrated long.",
        "symptom": "All positions red simultaneously on a single risk-off day.",
        "mitigation": "Stress-test under correlation=1 scenario; size for the bad case; hold tail hedges that pay out in stress.",
        "severity": 4,
        "references": ["Longin & Solnik (2001) Extreme Correlation of International Equity Markets"],
        "tags": ["correlation", "crisis", "diversification"],
    },

    # ----- Data quality -----
    {
        "id": "l_021",
        "category": "data_quality",
        "title": "Yahoo Finance adjustment errors",
        "description": "Free data providers occasionally misadjust for splits/dividends, producing spurious gaps and incorrect returns.",
        "symptom": "Backtest shows occasional large one-day gains/losses that aren't in your broker's chart.",
        "mitigation": "Cross-check with at least one other source; flag |daily return| > 30% for manual review.",
        "severity": 3,
        "references": ["Personal experience of every retail quant"],
        "tags": ["data_quality", "free_data"],
    },
    {
        "id": "l_022",
        "category": "data_quality",
        "title": "Point-in-time vs as-reported fundamentals",
        "description": "Fundamentals databases that don't track revisions let you backtest as if you knew the final restated numbers in real time. Inflates returns 1-3% annually.",
        "symptom": "Value/quality strategies backtest much better than they live-trade.",
        "mitigation": "Use point-in-time fundamentals (Compustat, Sharadar, S&P Capital IQ).",
        "severity": 4,
        "references": ["López de Prado (2018) ch 4"],
        "tags": ["data_quality", "fundamentals"],
    },

    # ----- Behavioral overrides -----
    {
        "id": "l_023",
        "category": "behavioral",
        "title": "Discretionary override of systematic stops",
        "description": "Operator overrides a stop because 'it'll come back'. Sometimes it does; the time it doesn't kills the strategy.",
        "symptom": "Manual position closures / extensions in the trade log.",
        "mitigation": "Either trade fully systematic or fully discretionary. Don't mix without a written protocol.",
        "severity": 4,
        "references": ["Tharp (2007)"],
        "tags": ["behavioral", "stops"],
    },
    {
        "id": "l_024",
        "category": "behavioral",
        "title": "Revenge trading after a loss",
        "description": "After a loss, operator increases size or breaks rules to 'win it back'. Compounds the original loss.",
        "symptom": "Position size rises right after a loss; rule violations cluster post-drawdown.",
        "mitigation": "Hard-coded cooldown after losses (already in src/risk/countermeasures.py).",
        "severity": 4,
        "references": ["Lo (2017) Adaptive Markets"],
        "tags": ["behavioral", "psychology"],
    },
    {
        "id": "l_025",
        "category": "behavioral",
        "title": "Confirmation bias in backtest interpretation",
        "description": "Operator tweaks strategy until backtest looks good. Each tweak is a free parameter; the model is fit to noise.",
        "symptom": "Many small parameter changes between backtest version A and 'final' version.",
        "mitigation": "Lock the strategy parameters before seeing any out-of-sample data. Walk-forward CV with frozen hyperparameters.",
        "severity": 4,
        "references": ["López de Prado (2018) ch 11"],
        "tags": ["behavioral", "backtest"],
    },

    # ----- Macro shocks -----
    {
        "id": "l_026",
        "category": "macro",
        "title": "Russia default 1998",
        "description": "Russia defaulted on sovereign debt, triggering flight to quality. EM bonds collapsed; LTCM convergence trades blew up.",
        "symptom": "EM credit spreads widening 200+ bps in days.",
        "mitigation": "Cap EM exposure; have tail-risk hedges; reduce leverage when global liquidity tightens.",
        "severity": 4,
        "references": ["Lowenstein (2000)"],
        "tags": ["macro", "em", "crisis"],
    },
    {
        "id": "l_027",
        "category": "macro",
        "title": "Swiss Franc removal of EUR peg (Jan 15, 2015)",
        "description": "SNB removed its 1.20 EUR/CHF floor without warning. CHF rallied 20% in minutes. Many FX retail brokers and several hedge funds went bankrupt overnight.",
        "symptom": "Carry/peg trades with 'no risk' in central bank guidance.",
        "mitigation": "Never assume any central bank commitment is permanent. Cap exposure to pegged regimes.",
        "severity": 5,
        "references": ["Various 2015 broker bankruptcy filings"],
        "tags": ["fx", "macro", "tail_risk"],
    },
    {
        "id": "l_028",
        "category": "macro",
        "title": "COVID-19 March 2020 vol spike",
        "description": "VIX hit 82 (vs ~12 normal). Most vol-targeting strategies cut leverage at exactly the wrong time; many short-vol funds blew up.",
        "symptom": "Realized vol moves multiple standard deviations above your training distribution.",
        "mitigation": "Vol-target with a floor; don't blindly de-leverage to zero in panics.",
        "severity": 4,
        "references": ["Multiple 2020 fund letters"],
        "tags": ["vol", "macro", "crisis"],
    },

    # ----- Counterparty -----
    {
        "id": "l_029",
        "category": "counterparty",
        "title": "MF Global bankruptcy (2011)",
        "description": "MF Global misused $1.6B of customer segregated funds. Customers got back ~89% after years of legal process.",
        "symptom": "Broker with rapidly deteriorating balance sheet or repeated regulatory actions.",
        "mitigation": "Don't keep more than 2-3 months of trading capital at any single broker. Use SIPC-insured brokers.",
        "severity": 4,
        "references": ["CFTC Order 2013"],
        "tags": ["counterparty", "broker"],
    },
    {
        "id": "l_030",
        "category": "counterparty",
        "title": "Crypto exchange insolvencies (Mt. Gox, FTX)",
        "description": "Customer funds commingled, lent out, or stolen. Mt. Gox lost 850k BTC in 2014; FTX lost $8B+ in 2022.",
        "symptom": "Exchange offering yields on customer balances; withdrawal delays; founder spending lavishly.",
        "mitigation": "Self-custody all crypto. Use exchanges only for active trading.",
        "severity": 5,
        "references": ["FTX bankruptcy filings"],
        "tags": ["counterparty", "crypto"],
    },

    # ----- Deployment / operational -----
    {
        "id": "l_031",
        "category": "deployment",
        "title": "Cron job in wrong timezone",
        "description": "Strategy scheduled in local time runs at the wrong UTC time after DST shift, missing or doubling executions.",
        "symptom": "Trade execution times shift by 1h around DST changes.",
        "mitigation": "Run cron in UTC; verify scheduled times in UTC explicitly.",
        "severity": 3,
        "references": ["Common SRE postmortem pattern"],
        "tags": ["operational", "scheduling"],
    },
    {
        "id": "l_032",
        "category": "deployment",
        "title": "API key with too-broad permissions",
        "description": "Trading bot's API key has withdrawal permission. Compromised key drains the account.",
        "symptom": "API key has more scopes than the bot needs.",
        "mitigation": "Use trading-only keys; never enable withdrawals via API. Rotate keys regularly.",
        "severity": 5,
        "references": ["Multiple exchange post-breach reports"],
        "tags": ["security", "api"],
    },
    {
        "id": "l_033",
        "category": "deployment",
        "title": "No idempotency on order placement",
        "description": "Retry after network timeout sends duplicate orders. End up with 2x intended position.",
        "symptom": "Filled qty exceeds requested qty.",
        "mitigation": "Use client_order_id deduplication on every order (already done in src/execution/broker.py).",
        "severity": 4,
        "references": ["Standard distributed systems pattern"],
        "tags": ["operational", "execution"],
    },

    # ----- Options-specific -----
    {
        "id": "l_034",
        "category": "execution",
        "title": "Assignment risk on short ITM options",
        "description": "Short ITM options can be assigned anytime before expiration. Surprise assignment over a weekend = directional exposure you didn't want.",
        "symptom": "Holding short ITM options past pin date.",
        "mitigation": "Close short ITM options 2+ days before expiration. Avoid Friday holding of short calls on ex-div names.",
        "severity": 3,
        "references": ["OCC Options Education"],
        "tags": ["options", "assignment"],
    },
    {
        "id": "l_035",
        "category": "execution",
        "title": "Volatility risk premium evaporates around events",
        "description": "Selling premium into earnings/FOMC ignores that IV is high for a reason. Realized vol often exceeds priced vol on the event.",
        "symptom": "Short-vol strategies repeatedly lose around earnings.",
        "mitigation": "Filter out trades within ±2 days of scheduled events. Read EarningsHub or Finnhub calendar.",
        "severity": 3,
        "references": ["Coval & Shumway (2001)"],
        "tags": ["options", "events"],
    },

    # ----- ML-specific -----
    {
        "id": "l_036",
        "category": "overfitting",
        "title": "Hyperparameter tuning on the same data you validate on",
        "description": "Pick best hyperparameters by CV score, then report that CV score. The CV is no longer unbiased — you've used it for selection.",
        "symptom": "Reported CV scores feel 'just right' across many trial configs.",
        "mitigation": "Hold out a final test set never touched during tuning. Report performance on it once.",
        "severity": 4,
        "references": ["López de Prado (2018) ch 9"],
        "tags": ["ml", "cv"],
    },
    {
        "id": "l_037",
        "category": "overfitting",
        "title": "Model has more parameters than samples after labeling",
        "description": "XGBoost with 1000 trees on 500 samples will memorize noise. Same for deep networks on small labeled finance datasets.",
        "symptom": "Train accuracy » CV accuracy.",
        "mitigation": "Constrain complexity (depth, n_estimators, regularization); use early stopping; favor simpler models for small data.",
        "severity": 4,
        "references": ["López de Prado (2018) ch 6"],
        "tags": ["ml", "overfitting"],
    },
    {
        "id": "l_038",
        "category": "regime_shift",
        "title": "Model not retrained as regime changes",
        "description": "Model trained on 2010-2019 (low-rate, low-vol) performed terribly in 2020-2022 (vol regime + rate hikes).",
        "symptom": "Model accuracy degrades over time on rolling out-of-sample.",
        "mitigation": "Schedule monthly retraining. Monitor feature distribution drift.",
        "severity": 4,
        "references": ["Standard MLOps practice"],
        "tags": ["ml", "regime", "mlops"],
    },
    {
        "id": "l_039",
        "category": "data_quality",
        "title": "Class imbalance in labels",
        "description": "Long forward returns are 53% of samples but model predicts 80% long. Accuracy looks decent but precision/recall asymmetric.",
        "symptom": "Most predictions are the majority class.",
        "mitigation": "Class-weight balancing; sample weighting; or use AUC instead of accuracy.",
        "severity": 3,
        "references": ["Standard ML practice"],
        "tags": ["ml", "imbalance"],
    },

    # ----- Position management -----
    {
        "id": "l_040",
        "category": "risk_sizing",
        "title": "Pyramiding into winners without stop adjustment",
        "description": "Adding to winners is fine, but if the original stop isn't tightened, the entire position is now exposed to a deeper loss than originally sized for.",
        "symptom": "Position size growing while stop distance unchanged.",
        "mitigation": "Trail stops as adds occur; re-compute position-level risk after every add.",
        "severity": 3,
        "references": ["Chan (2008)"],
        "tags": ["sizing", "pyramiding"],
    },
    {
        "id": "l_041",
        "category": "execution",
        "title": "Overnight gap risk on swing trades",
        "description": "Stops don't trigger on gaps. A 5% stop becomes a 15% loss if the stock gaps down on earnings overnight.",
        "symptom": "Realized losses materially larger than stop-loss intent.",
        "mitigation": "Reduce or close before earnings/news events. Use options for defined-risk overnight exposure.",
        "severity": 4,
        "references": ["Common retail blowup pattern"],
        "tags": ["overnight", "gap", "earnings"],
    },
    {
        "id": "l_042",
        "category": "behavioral",
        "title": "Drawdown psychology: cutting size mid-drawdown",
        "description": "When in drawdown, operator cuts size by 50%. When strategy recovers, they're under-sized for the rebound and never make it back.",
        "symptom": "Position sizes shrink during DD but don't restore quickly.",
        "mitigation": "Pre-commit to a vol-targeting rule. Don't manually intervene in sizing.",
        "severity": 3,
        "references": ["Kahneman & Tversky (1979)"],
        "tags": ["behavioral", "drawdown"],
    },

    # ----- Crowdedness / structural -----
    {
        "id": "l_043",
        "category": "crowding",
        "title": "Risk parity unwinds in 2020 / 2022",
        "description": "Risk-parity funds had built up huge bond positions in a low-vol regime. When bond vol spiked, all sold simultaneously — bonds fell while equities also fell. Diversification benefit reversed.",
        "symptom": "Bonds and stocks both falling on the same day (broken correlation regime).",
        "mitigation": "Don't assume historical -0.3 stock-bond correlation persists. Stress-test under +1 scenario.",
        "severity": 4,
        "references": ["Bridgewater 2020 letter"],
        "tags": ["crowding", "risk_parity"],
    },
    {
        "id": "l_044",
        "category": "macro",
        "title": "Negative oil price (April 20, 2020)",
        "description": "WTI front-month futures settled at -$37.63 due to storage constraints + futures roll mechanics. Many retail oil ETF holders wiped out.",
        "symptom": "Futures backwardation extreme; storage at capacity; settlement approaching.",
        "mitigation": "Don't hold front-month commodity futures over settlement. Avoid leveraged commodity ETFs for >1 day.",
        "severity": 5,
        "references": ["CFTC retrospective"],
        "tags": ["commodities", "futures", "tail_risk"],
    },

    # ----- Crypto-specific -----
    {
        "id": "l_045",
        "category": "regime_shift",
        "title": "Crypto winters",
        "description": "Crypto can drop 80-90% over 12-18 months (2014, 2018, 2022). Trend-following looks excellent in bull, brutal in bear.",
        "symptom": "Trend-following crypto strategy with high Sharpe in 2020-2021 backtest.",
        "mitigation": "Backtest across at least one crypto winter. Include 2014-2015 in any crypto backtest.",
        "severity": 4,
        "references": ["Cryptocurrency market history"],
        "tags": ["crypto", "regime"],
    },

    # ----- Operational hygiene -----
    {
        "id": "l_046",
        "category": "deployment",
        "title": "No paper-trading period before live",
        "description": "Strategy goes from backtest to live with no paper-trading validation. First live week reveals 3 bugs that erase 20% of starting capital.",
        "symptom": "Strategy goes live without 4+ weeks of paper validation.",
        "mitigation": "Mandatory paper period before live (enforced by the promotion gate in this repo).",
        "severity": 5,
        "references": ["Universal practitioner consensus"],
        "tags": ["deployment", "process"],
    },
    {
        "id": "l_047",
        "category": "behavioral",
        "title": "Over-monitoring causes intervention",
        "description": "Watching every tick triggers emotional responses. Operator overrides systematic decisions based on noise.",
        "symptom": "Operator checking P&L > 5x/hour during trading.",
        "mitigation": "Look at dashboard 2x/day (morning + close). Set alerts for hard breaches only.",
        "severity": 3,
        "references": ["Tharp (2007)"],
        "tags": ["behavioral", "psychology"],
    },
    {
        "id": "l_048",
        "category": "data_quality",
        "title": "Feature distribution drift",
        "description": "Features that were stationary in training become non-stationary live (e.g., VIX regime shift, structural change in spread). Model becomes uncalibrated.",
        "symptom": "Live feature mean/std differs >2 sigma from training distribution.",
        "mitigation": "Monitor feature drift weekly. Retrain when drift exceeds threshold.",
        "severity": 4,
        "references": ["Standard MLOps pattern"],
        "tags": ["data_quality", "drift"],
    },
    {
        "id": "l_049",
        "category": "execution",
        "title": "Order types confused (market vs limit vs stop)",
        "description": "Marketable limit confused with market; stop-limit not filled because limit was too tight in fast market.",
        "symptom": "Stops don't fill when expected; limits cross book and become market.",
        "mitigation": "Document order type semantics per broker; test each type explicitly before live.",
        "severity": 3,
        "references": ["Broker documentation, every retail forum"],
        "tags": ["execution", "order_types"],
    },
    {
        "id": "l_050",
        "category": "overfitting",
        "title": "Selection bias in 'best strategy' from many backtests",
        "description": "Test 100 strategies, the best by Sharpe will have Sharpe 2.5 even on pure noise. Picking it doesn't mean it's good.",
        "symptom": "Final strategy is the best of many tried; CV scores cluster near top of distribution.",
        "mitigation": "Pre-register hypotheses. Use deflated Sharpe. Walk-forward fold-by-fold accuracy must be consistent, not just average.",
        "severity": 5,
        "references": ["Harvey, Liu, Zhu (2016)",
                       "Bailey & López de Prado (2014)"],
        "tags": ["overfitting", "selection_bias", "process"],
    },

    # ----- A few more domain-specific -----
    {
        "id": "l_051",
        "category": "execution",
        "title": "Partial fills on bracket orders",
        "description": "Bracket order fills 50%; the take-profit and stop-loss apply to the full ordered qty, not the filled qty, on some brokers.",
        "symptom": "Stop or TP attached to qty larger than actual position; broker error or unintended naked exposure.",
        "mitigation": "Verify broker's bracket semantics; cancel and re-submit on partial fill if needed.",
        "severity": 3,
        "references": ["Alpaca docs"],
        "tags": ["execution", "options", "brackets"],
    },
    {
        "id": "l_052",
        "category": "data_quality",
        "title": "Free APIs returning stale data silently",
        "description": "Yahoo / Finnhub free tiers occasionally return delayed or stale prices without error. Your model thinks it has live data; it doesn't.",
        "symptom": "Prices in your data feed lag the broker's quote by >5 minutes.",
        "mitigation": "Cross-check timestamp of every quote vs system clock; flag stale data; never trade on data >5min old.",
        "severity": 3,
        "references": ["Personal experience"],
        "tags": ["data_quality", "free_data"],
    },
]
