"""Bootstrap the signal calibrator from backtest trade data.

The live SignalCalibrator needs 5+ closed trades per confidence bucket before
it activates. With zero live closed trades it passes every confidence value
through unchanged — no learning benefit.

This script builds an empirical prior from the 270k+ backtest trades in
data/all_trades.csv.  Since all_trades.csv was generated by the same ensemble
pipeline, its win rates by direction and scenario are real signal quality
measurements.

Strategy
--------
The backtest CSV has no per-trade confidence column, but we can construct
meaningful bucket priors using two facts from learned_params.json:

  long  win_rate = 66.7%   expected_R = +0.996
  short win_rate = 21.1%   expected_R = -0.371

and from the ensemble design:
  - Signals at or above 0.75 threshold are high-conviction
  - Confluence/Breakout models produce 0.82–0.92 for strong setups
  - Most passing long signals cluster in [0.75, 0.92]

We build confidence buckets by grouping backtest trades by direction and
scenario difficulty, then assign estimated confidence ranges:
  - Signals from easy/trending scenarios → lower confidence (0.75–0.82)
  - Signals from brutal/crash scenarios → higher confidence required (0.82–0.93)
  - Apply measured win rate per bucket as the calibration prior

Output: data/calibration_bootstrap.json
The SignalCalibrator loads this file at startup as a warm prior, then
overwrites buckets as real live trade data accumulates (5+ trades/bucket).

Usage
-----
    python scripts/bootstrap_calibrator.py
    python scripts/bootstrap_calibrator.py --csv data/all_trades.csv
"""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)

ROOT      = Path(__file__).resolve().parent.parent
DATA_DIR  = ROOT / "data"
OUT_PATH  = DATA_DIR / "calibration_bootstrap.json"
PARAMS    = DATA_DIR / "learned_params.json"
BUCKET    = 0.05
ALPHA     = 0.40   # must match signal_calibrator.py


def build_bootstrap(csv_path: Path) -> dict:
    """Build calibration map from backtest CSV.

    Returns a dict: { "0.75": scale, "0.80": scale, ... }
    """
    df = pd.read_csv(csv_path)
    df["won"] = df["pnl"] > 0

    # ── Load known win rates from learned_params ───────────────────────
    if PARAMS.exists():
        p = json.loads(PARAMS.read_text())
        long_wr  = float(p.get("by_direction", {}).get("long", {}).get("win_rate", 0.597))
        short_wr = float(p.get("by_direction", {}).get("short", {}).get("win_rate", 0.213))
    else:
        long_wr  = df[df.direction == "long"]["won"].mean()
        short_wr = df[df.direction == "short"]["won"].mean()

    logger.info("Empirical win rates — long: %.1f%%  short: %.1f%%",
                long_wr * 100, short_wr * 100)

    # ── Map scenario difficulty → estimated confidence bucket ──────────
    # We infer signal difficulty from scenario type. Harder scenarios require
    # higher-conviction signals; the ensemble typically assigns these to
    # higher confidence buckets.
    difficulty_conf_map = {
        "mild":     (0.75, 0.80),
        "moderate": (0.80, 0.85),
        "severe":   (0.85, 0.90),
        "brutal":   (0.88, 0.93),
    }
    default_range = (0.75, 0.85)

    calibration: dict = {}

    # ── Process by direction + difficulty ─────────────────────────────
    for direction in ("long", "short"):
        sub = df[df.direction == direction]
        if sub.empty:
            continue
        overall_wr = sub["won"].mean()

        # Group by scenario difficulty if the column exists
        if "difficulty" in sub.columns:
            for diff, (lo, hi) in difficulty_conf_map.items():
                rows = sub[sub["difficulty"] == diff]
                if len(rows) < 10:
                    continue
                wr = rows["won"].mean()
                # Assign win rate to buckets in the estimated confidence range
                buckets = np.arange(lo, hi, BUCKET)
                for b in buckets:
                    b = round(float(b), 4)
                    # Blend: 70% from this difficulty, 30% from overall direction WR
                    blended_wr = 0.70 * wr + 0.30 * overall_wr
                    scale = 1.0 + (blended_wr - 0.50) * 2 * ALPHA
                    scale = float(np.clip(scale, 0.70, 1.40))
                    # Average with existing if already set
                    if b in calibration:
                        calibration[b] = (calibration[b] + scale) / 2
                    else:
                        calibration[b] = scale
                    logger.debug(
                        "  [%s/%s] conf_bucket=%.2f  n=%d  wr=%.1f%%  scale=%.3f",
                        direction, diff, b, len(rows), blended_wr * 100, scale,
                    )
        else:
            # No difficulty column — use direction WR for the canonical range.
            # For the above-threshold range (0.75+) we ONLY use long WR because
            # side_bias blocks shorts in trending_up regimes — averaging short
            # WR in would unfairly penalise the long calibration buckets.
            if direction == "short":
                continue   # skip short direction — longs dominate above 0.75
            lo, hi = default_range
            for b in np.arange(lo, hi, BUCKET):
                b = round(float(b), 4)
                scale = 1.0 + (overall_wr - 0.50) * 2 * ALPHA
                scale = float(np.clip(scale, 0.70, 1.40))
                # Only set if not already computed from a more specific source
                if b not in calibration:
                    calibration[b] = scale

    # ── Also add the sub-threshold buckets (0.50–0.75) from data ──────
    # These should be suppressed but we calibrate them downward just in case.
    sub_threshold_wr = df[df.direction == "long"]["won"].mean() * 0.70  # penalised
    for b in np.arange(0.50, 0.75, BUCKET):
        b = round(float(b), 4)
        scale = 1.0 + (sub_threshold_wr - 0.50) * 2 * ALPHA
        scale = float(np.clip(scale, 0.70, 1.0))   # sub-threshold never gets boosted
        if b not in calibration:
            calibration[b] = scale

    # ── Summary ───────────────────────────────────────────────────────
    logger.info("Built %d calibration buckets", len(calibration))
    for b in sorted(calibration):
        logger.info("  %.2f–%.2f  →  scale=%.4f", b, b + BUCKET, calibration[b])

    return {f"{b:.2f}": round(v, 4) for b, v in sorted(calibration.items())}


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap signal calibrator from backtest trades.")
    parser.add_argument("--csv", default=str(DATA_DIR / "all_trades.csv"),
                        help="Path to all_trades.csv (default: data/all_trades.csv)")
    parser.add_argument("--out", default=str(OUT_PATH),
                        help="Output JSON path")
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        logger.error("CSV not found: %s", csv_path)
        raise SystemExit(1)

    logger.info("Building calibration bootstrap from %s (%d rows)...",
                csv_path.name, sum(1 for _ in csv_path.open()) - 1)

    cal = build_bootstrap(csv_path)
    out = Path(args.out)
    out.write_text(json.dumps({
        "source":    "bootstrap",
        "csv_rows":  int(pd.read_csv(csv_path).shape[0]),
        "generated": __import__("datetime").datetime.utcnow().isoformat() + "Z",
        "alpha":     ALPHA,
        "bucket_size": BUCKET,
        "calibration": cal,
    }, indent=2))
    logger.info("Wrote bootstrap calibration → %s", out)


if __name__ == "__main__":
    main()
